-- =====================================================================
--  📚 অফিসিয়াল ৬০টি প্রশ্ন — উত্তরবঙ্গ হেরিটেজ ফেস্ট ২০২৬
--  Primary (৩য়–৫ম) · Junior (৬ষ্ঠ–৮ম) · Senior (৯ম–১০ম) — ২০টি করে
--
--  ⚠️ এই স্ক্রিপ্টটি questions টেবিলের পুরনো সব প্রশ্ন মুছে ফেলে,
--  তারপর ৬০টি অফিসিয়াল প্রশ্ন বসায় (replace-all সেমেন্টিক্স)।
--  আবার চালালেও ফলাফল একই (idempotent)।
--
--  কোথায়: Supabase → SQL Editor → পুরোটা পেস্ট → Run
--  (প্রশ্ন লেখা শুধু আয়োয়কের — তাই REST দিয়ে নয়, SQL Editor দিয়ে চালাও)
-- =====================================================================

delete from public.questions;

-- ---------- Primary ----------
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'রংপুর বিভাগে মোট কয়টি জেলা আছে? / How many districts are there in Rangpur Division?', '৬টি | 6', '৭টি | 7', '৮টি | 8', '৯টি | 9', 'C', 1, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'রংপুর কত সালে বাংলাদেশের সপ্তম বিভাগ হিসেবে ঘোষিত হয়? / In which year was Rangpur declared the 7th division of Bangladesh?', '২০০৫ | 2005', '২০১০ | 2010', '২০১৫ | 2015', '২০২০ | 2020', 'B', 2, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'বাংলাদেশের সবচেয়ে উত্তরের জেলা কোনটি? / Which is the northernmost district of Bangladesh?', 'রংপুর | Rangpur', 'দিনাজপুর | Dinajpur', 'পঞ্চগড় | Panchagarh', 'গাইবান্ধা | Gaibandha', 'C', 3, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'পঞ্চগড় জেলা থেকে হিমালয়ের কোন চূড়া দেখা যায়? / Which Himalayan peak can be seen from Panchagarh?', 'মাউন্ট এভারেস্ট | Mount Everest', 'কে-টু | K2', 'অন্নপূর্ণা | Annapurna', 'কাঞ্চনজঙ্ঘা | Kanchenjunga', 'D', 4, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'বাংলাদেশের ''রুটির ঝুড়ি'' বলা হয় কোন জেলাকে? / Which district is called the ''bread basket'' of Bangladesh?', 'ঠাকুরগাঁও | Thakurgaon', 'কুড়িগ্রাম | Kurigram', 'নীলফামারী | Nilphamari', 'লালমনিরহাট | Lalmonirhat', 'A', 5, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'রংপুরকে কী নামে ডাকা হয়? / By what name is Rangpur called?', 'সোনার দেশ | Golden Land', 'বাহের দেশ | Baher Desh', 'চায়ের দেশ | Land of Tea', 'নদীর দেশ | Land of Rivers', 'B', 6, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'মুক্তিযুদ্ধের সময় কোন উপজেলায় মুক্তিযোদ্ধাদের ট্রেনিং ক্যাম্প ছিল? / In which upazila was a freedom fighters'' training camp located during the Liberation War?', 'রৌমারী | Roumari', 'উলিপুর | Ulipur', 'নাগেশ্বরী | Nageshwari', 'ফুলবাড়ী | Phulbari', 'A', 7, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'পঞ্চগড়ের কোন স্থলবন্দর চালু রয়েছে? / Which land port is operating in Panchagarh?', 'বেনাপোল | Benapole', 'বুড়িমারী | Burimari', 'সোনামসজিদ | Sonamasjid', 'বাংলাবান্ধা | Banglabandha', 'D', 8, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'গাইবান্ধা জেলা কয়টি উপজেলায় বিভক্ত? / Into how many upazilas is Gaibandha divided?', '৫টি | 5', '৬টি | 6', '৭টি | 7', '৮টি | 8', 'C', 9, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'কুড়িগ্রাম জেলায় উপজেলার সংখ্যা কয়টি? / How many upazilas are there in Kurigram?', '৯টি | 9', '৭টি | 7', '৮টি | 8', '১০টি | 10', 'A', 10, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'রংপুরের বিখ্যাত আমের নাম কী? / What is the famous mango of Rangpur?', 'হিমসাগর | Himsagar', 'হাড়িভাঙ্গা | Haribhanga', 'ল্যাংড়া | Langra', 'গোপালভোগ | Gopalbhog', 'B', 11, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'রংপুর কোন ঐতিহ্যবাহী পণ্যের জন্য বিখ্যাত? / Rangpur is famous for which traditional product?', 'জামদানি | Jamdani', 'নকশিকাঁথা | Nakshi Kantha', 'মসলিন | Muslin', 'শতরঞ্জি | Shataranji', 'D', 12, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', '''পঞ্চগড়'' নামের ''পঞ্চ'' শব্দের অর্থ কী? / What does ''Pancha'' in ''Panchagarh'' mean?', 'পাঁচ | Five', 'তিন | Three', 'সাত | Seven', 'দশ | Ten', 'A', 13, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'নীলফামারী অঞ্চলে ইংরেজ নীলকররা কিসের চাষের খামার স্থাপন করে? / What crop''s farms did British planters set up in Nilphamari?', 'ধান | Rice', 'নীল | Indigo', 'পাট | Jute', 'চা | Tea', 'B', 14, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'লালমনিরহাট জেলায় মোট কয়টি উপজেলা রয়েছে? / How many upazilas are there in Lalmonirhat?', '৫টি | 5', '৩টি | 3', '৪টি | 4', '৬টি | 6', 'A', 15, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'বাংলা সাহিত্যের প্রাচীনতম নিদর্শন কোনটি? / What is the oldest specimen of Bengali literature?', 'শ্রীকৃষ্ণকীর্তন', 'মঙ্গলকাব্য', 'গীতাঞ্জলি', 'চর্যাপদ | Charyapada', 'D', 16, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'পঞ্চগড় শহরের স্টেডিয়ামটি কার নামে পরিচিত? / After whom is Panchagarh town''s stadium named?', 'বঙ্গবন্ধু স্টেডিয়াম', 'শেখ রাসেল স্টেডিয়াম', 'বীর মুক্তিযোদ্ধা সিরাজুল ইসলাম স্টেডিয়াম', 'শহীদ সামাদ স্টেডিয়াম', 'C', 17, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'ক্রিকেটার শরিফুল ইসলাম কোন জেলায় জন্মগ্রহণ করেন? / In which district was cricketer Shariful Islam born?', 'দিনাজপুর', 'পঞ্চগড় | Panchagarh', 'রংপুর', 'গাইবান্ধা', 'B', 18, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'রংপুরে অবস্থিত সরকারি বিশ্ববিদ্যালয়ের নাম কী? / What is the public university located in Rangpur?', 'ঢাকা বিশ্ববিদ্যালয়', 'রাজশাহী বিশ্ববিদ্যালয়', 'বেগম রোকেয়া বিশ্ববিদ্যালয় | Begum Rokeya University', 'জাহাঙ্গীরনগর বিশ্ববিদ্যালয়', 'C', 19, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Primary', 'পঞ্চগড়ের সমতলে সম্প্রতি কোন ফসলের বাণিজ্যিক চাষ শুরু হয়েছে? / Which crop has recently begun to be grown commercially on Panchagarh''s plains?', 'চা | Tea', 'কফি | Coffee', 'রাবার | Rubber', 'কোকো | Cocoa', 'A', 20, 'official');

-- ---------- Junior ----------
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'আয়তন অনুযায়ী রংপুর বিভাগের বৃহত্তম জেলা কোনটি? / Which is the largest district of Rangpur Division by area?', 'রংপুর', 'দিনাজপুর | Dinajpur', 'কুড়িগ্রাম', 'গাইবান্ধা', 'B', 1, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'লালমনিরহাট নামকরণের একটি মত অনুযায়ী ১৭৮৩ সালে ব্রিটিশদের বিরুদ্ধে লড়ে প্রাণ দেন কোন নারী কৃষক নেত্রী? / Which woman peasant leader died fighting the British in 1783?', 'রোকেয়া', 'শ্যামাসুন্দরী', 'লালমনি | Lalmoni', 'দেবী চৌধুরানী', 'C', 2, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', '''নীলফামারী'' নামটি কোন শব্দের অপভ্রংশ? / ''Nilphamari'' is a corrupted form of which term?', 'নীল খামারী | Nil Khamari', 'নীলকণ্ঠ', 'নীলাম্বর', 'নীলধ্বজ', 'A', 3, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', '১৯৭১ সালের ২ অক্টোবর পাকিস্তানিরা কতজন বেসামরিক মানুষকে বেঁধে খারুভাঞ্জ ক্যাম্পে নিয়ে যায়? / How many civilians were tied up and taken to Kharuvanj camp on 2 October 1971?', '৫৩ জন', '৫৭ জন', '৬৫ জন | 65', '৮০ জন', 'C', 4, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'মুক্তিযুদ্ধের সময় জিয়াউর রহমান তিন মাসের বেশি সময় কোথায় ডাক বাংলোতে ছিলেন? / Where did Ziaur Rahman stay in a dak bungalow for over three months during the war?', 'উলিপুর', 'চিলমারী', 'রাজারহাট', 'রৌমারী | Roumari', 'D', 5, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'বড়াইবাড়ি সীমান্ত সংঘর্ষে কতজন বাংলাদেশি সীমান্তরক্ষী নিহত হন? / How many Bangladeshi border guards were killed in the Baraibari clash?', '১ জন', '২ জন | 2', '১৬ জন', '১৭০ জন', 'B', 6, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'কুড়িগ্রাম মহকুমা কত সালে গঠিত হয়? / In which year was Kurigram subdivision established?', '১৮৭৫ | 1875', '১৮৫৮', '১৮৬৯', '১৯১১', 'A', 7, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'রংপুরের শ্যামাসুন্দরী খাল পুনঃখনন করেন কে? / Who re-excavated the Shyamasundari canal in Rangpur?', 'রাজা গণেশ', 'রাজা জানকীবল্লভ সেন | Raja Janakiballabh Sen', 'রাজা মানসিংহ', 'মহারাজা বিশ্ব সিংহ', 'B', 8, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'বইয়ের তথ্য অনুযায়ী দিনাজপুর নামটি কার নাম থেকে এসেছে? / According to the book, ''Dinajpur'' originated from whose name?', 'রাজা গণেশ', 'যদুনারায়ণ খাঁ', 'পেস্কার দিনরাজ | Peshkar Dinraj', 'রাজা পৃথু', 'C', 9, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'পঞ্চগড় কবে জেলা হিসেবে উন্নীত হয়? / When was Panchagarh upgraded to a district?', '১ জানুয়ারি ১৯৮০', '১ ফেব্রুয়ারি ১৯৮১', '২৫ জানুয়ারি ২০১০', '১ ফেব্রুয়ারি ১৯৮৪ | 1 Feb 1984', 'D', 10, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'ঠাকুরগাঁও জেলা কোন শস্য উৎপাদনে দেশে শীর্ষে? / Thakurgaon is top in Bangladesh in producing which crop?', 'ধান', 'গম | Wheat', 'পাট', 'আখ', 'B', 11, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'ঠাকুরগাঁও নামের সঙ্গে জড়িত চক্রবর্তী বাড়িকে স্থানীয়রা কী বলত? / What did locals call the Chakraborty house linked to ''Thakurgaon''?', 'ঠাকুরবাড়ি | Thakurbari', 'রাজবাড়ি', 'জমিদারবাড়ি', 'নিশ্চিন্তবাড়ি', 'A', 12, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'গাইবান্ধা জেলা কত সালে গঠিত হয়? / In which year was Gaibandha district formed?', '১৯২৩', '১৯৬০', '১৯৭৩', '১৯৮৪ | 1984', 'D', 13, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'কিংবদন্তি অনুযায়ী গোবিন্দগঞ্জে কোন রাজার রাজধানী ছিল, যাঁর প্রায় ৬০ হাজার গাভী ছিল? / Which king with ~60,000 cows had his capital at Gobindaganj?', 'বিরাট রাজা | King Virata', 'রাজা গণেশ', 'রাজা পৃথু', 'রাজা শালিবাহন', 'A', 14, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'ঠাকুরগাঁও রেশম কারখানা কত সালে বন্ধ ঘোষণা করা হয়? / In which year was the Thakurgaon Silk Factory declared closed?', '১৯৭৬', '১৯৮১', '১৯৯৯', '২০০২ | 2002', 'D', 15, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'পঞ্চগড় জেলার প্রথম বৃহৎ শিল্প প্রতিষ্ঠান কোনটি? / Which was the first large industry in Panchagarh?', 'জেমকন লিমিটেড', 'মার্শাল ডিস্টিলারী', 'জেমজুট লিমিটেড', 'পঞ্চগড় সুগার মিলস লিমিটেড | Panchagarh Sugar Mills Ltd.', 'D', 16, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'ভারত ভাগের সময় পঞ্চগড়ের সীমানা নির্ধারণ করেন কে? / Who determined Panchagarh''s borders during the 1947 Partition?', 'লর্ড মাউন্টব্যাটেন', 'লর্ড কার্জন', 'স্যার সিরিল র‍্যাডক্লিফ | Sir Cyril Radcliffe', 'রবার্ট ক্লাইভ', 'C', 17, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'রংপুর কততম বিভাগীয় শহর? / Rangpur is which divisional city of Bangladesh?', '৭ম | 7th', '৫ম', '৬ষ্ঠ', '৮ম', 'A', 18, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'নিচের কোনটি ঠাকুরগাঁও জেলার নদী? / Which is a river of Thakurgaon district?', 'পদ্মা', 'টাঙ্গন | Tangon', 'মেঘনা', 'যমুনা', 'B', 19, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Junior', 'মুক্তিযুদ্ধের সময় পঞ্চগড় কোন সেক্টরের অন্তর্ভুক্ত ছিল? / Which sector did Panchagarh belong to in the Liberation War?', '৪নং সেক্টর', '৫নং সেক্টর', '৬নং সেক্টর | Sector 6', '৭নং সেক্টর', 'C', 20, 'official');

-- ---------- Senior ----------
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'পণ্ডিত জা পলিলুস্কির মতে বাংলায় ''কুড়ি'' হিসেবে গণনার পদ্ধতি কোন ভাষা থেকে এসেছে? / From which language did counting in ''kuri'' come?', 'কোল ভাষা | Kol', 'সংস্কৃত', 'ফারসি', 'আরবি', 'A', 1, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', '১৭শ শতাব্দীর মানচিত্রে টাঙ্গন নদীর কোন প্রান্তে নিশ্চিন্তপুর ও কোন প্রান্তে ঠাকুরগাঁও দেখানো হয়েছে? / On the 17th-century map, which bank of the Tangon shows Nishchintapur and Thakurgaon?', 'নিশ্চিন্তপুর পশ্চিমে, ঠাকুরগাঁও পূর্বে', 'নিশ্চিন্তপুর পূর্বে, ঠাকুরগাঁও পশ্চিমে | Nishchintapur east, Thakurgaon west', 'দুটিই পূর্বে', 'দুটিই পশ্চিমে', 'B', 2, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'ঠাকুরগাঁওয়ের আদি নাম ''নিশ্চিন্তপুর'' প্রমাণে কোন মানচিত্র ব্যবহৃত হয়েছে? / Which map proves Thakurgaon''s original name was ''Nishchintapur''?', '১৫শ শতাব্দীর গৌড়ের মানচিত্র', '১৭শ শতাব্দীর কোচবিহারের মানচিত্র | 17th-century map of Cooch Behar', '১৯শ শতাব্দীর ব্রিটিশ মানচিত্র', '১৯৪৭ সালের র‍্যাডক্লিফ মানচিত্র', 'B', 3, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', '১৯৮১ সালে পঞ্চগড় আলাদা মহকুমা হলে ঠাকুরগাঁও মহকুমা কয়টি থানায় সংকুচিত হয়? / Thakurgaon was reduced to how many thanas in 1981?', '৩টি', '৪টি', '৫টি | 5', '১০টি', 'C', 4, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'চর্যাপদ কোথা থেকে আবিষ্কৃত হয়েছে? / Where was the Charyapada discovered?', 'নেপালের রাজদরবার | Royal court of Nepal', 'কোচবিহারের রাজদরবার', 'গৌড়ের রাজদরবার', 'কামরূপের রাজদরবার', 'A', 5, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'চর্যাপদের কোন পদকর্তার সঙ্গে ঠাকুরগাঁওয়ের সংশ্লিষ্টতার কথা অনেকে সমর্থন করেছেন? / Which Charyapada poet is connected with Thakurgaon?', 'লুইপা', 'কাহ্নপা', 'ভুসুকুপা', 'গোরক্ষনাথ | Gorakshanath', 'D', 6, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'আকবরের সুবেবাংলার ১৯টি সরকারের মধ্যে কোন দুটি ঠাকুরগাঁও জেলার সীমানাভুক্ত ছিল? / Which two sarkars lay within Thakurgaon?', 'ঘোড়াঘাট ও তাজপুর', 'তাজপুর ও পাঞ্জারা | Tajpur & Panjara', 'পিঞ্জিরা ও ঘোড়াঘাট', 'গৌড় ও তান্ডা', 'B', 7, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'বৈগ্রামে প্রাপ্ত তাম্রলিপিটি কোন গুপ্ত সম্রাটের সময়ের? / The Baigram copper plate belongs to which Gupta emperor''s reign?', 'চন্দ্রগুপ্ত', 'সমুদ্রগুপ্ত', 'স্কন্দগুপ্ত', 'কুমার গুপ্ত | Kumar Gupta', 'D', 8, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'অশোকের পুণ্ড্ররাজ্য অধিকারের প্রমাণ কোথায় পাওয়া গেছে? / Where is evidence of Ashoka''s conquest of Pundra found?', 'চর্যাপদে', 'ঠাকুরগাঁওয়ে প্রাপ্ত বুদ্ধমূর্তিতে', 'রাজাগাঁওয়ে প্রাপ্ত মুদ্রায়', 'মহাস্থানগড়ে প্রাপ্ত ব্রাহ্মীলিপির শিলাখণ্ডলিপিতে | Brahmi stone inscription at Mahasthangarh', 'D', 9, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'কুড়িগ্রামে সেন রাজবংশের রাজধানী কোথায় ছিল? / Where was the Sen dynasty''s capital in Kurigram?', 'কোদালকাটি', 'রাজারহাটের বিদ্যানন্দ ইউনিয়নের চত্রা গ্রাম | Chatra village, Bidyananda Union, Rajarhat', 'শংকর মাধবপুর', 'রৌমারী', 'B', 10, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'কোম্পানি শাসনের শুরুতে রংপুর অঞ্চলে কোন বিদ্রোহ সংঘটিত হয়? / Which revolt occurred in Rangpur at the start of Company rule?', 'ফকির-সন্ন্যাসী বিদ্রোহ | Fakir-Sannyasi Rebellion', 'সাঁওতাল বিদ্রোহ', 'নীল বিদ্রোহ', 'সিপাহি বিদ্রোহ', 'A', 11, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'লালমনিরহাট সদরে প্রত্নতত্ত্ব অধিদপ্তরের তালিকাভুক্ত প্রত্নতাত্ত্বিক স্থাপনা কোনটি? / Which archaeological site in Lalmonirhat Sadar is listed?', 'ষাট গম্বুজ মসজিদ', 'নিদারিয়া মসজিদ | Nidaria Mosque', 'কান্তজির মন্দির', 'সোমপুর বিহার', 'B', 12, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'রংপুর পৌর কর্পোরেশন (পৌরসভা) কত সালে প্রতিষ্ঠিত হয়? / In which year was Rangpur''s municipal body established?', '১৮৬৯ | 1869', '১৭৬৯', '১৮৩২', '১৮৯২', 'A', 13, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'মুক্তিযুদ্ধে ৬নং সেক্টরের বেসামরিক উপদেষ্টা ছিলেন কে? / Who was civil adviser of Sector 6 in the Liberation War?', 'অ্যাড. সিরাজুল ইসলাম | Adv. Sirajul Islam', 'অ্যাড. কমরউদ্দিন আহমেদ', 'অ্যাড. মোশারফ হোসেন চৌধুরী', 'নাজিম উদ্দীন আহমেদ', 'A', 14, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', '১৯৭১ সালে কোন তারিখে দেবীগঞ্জ উপজেলা হানাদারমুক্ত হয়? / On which date in 1971 was Debiganj freed?', '২৯ নভেম্বর', '১ ডিসেম্বর', '২ ডিসেম্বর', '৯ ডিসেম্বর | 9 Dec', 'D', 15, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'নীলফামারী শহর কোন ভূ-প্রাকৃতিক অঞ্চলে অবস্থিত? / In which physiographic region is Nilphamari town located?', 'বরেন্দ্র ভূমি', 'মধুপুর গড়', 'তিস্তা প্লাবনভূমি | Teesta floodplain', 'সুন্দরবন', 'C', 16, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'ঠাকুরগাঁওয়ের কোচ, পলিয়া ও রাজবংশী জনগোষ্ঠী কোন নরগোষ্ঠীর বৈশিষ্ট্যসম্পন্ন? / The Koch, Polia and Rajbanshi have features of which racial group?', 'আদি-অস্ট্রেলীয়', 'অ্যালপাইন', 'মোঙ্গলীয় | Mongoloid', 'নিগ্রো', 'C', 17, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', 'প্রাকৃত ভাষার বৈশিষ্ট্য অনুযায়ী ''পঞ্চগড়'' নামের সম্ভাব্য ক্রমবিবর্তন কোনটি? / What is the likely evolution of the name ''Panchagarh''?', 'পঞ্চগৌড় > পঞ্চগোড় > পঞ্চগড় | Panchagaur > Panchagor > Panchagarh', 'পঞ্চগড় > পঞ্চগোড় > পঞ্চগৌড়', 'পঞ্চনগরী > পঞ্চগৌড় > পঞ্চগোড়', 'পঞ্চগোড় > পঞ্চগড় > পঞ্চগৌড়', 'A', 18, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', '১৯৭৬ সালে ঠাকুরগাঁওয়ে রেশম কারখানাটি কোন সংস্থা প্রতিষ্ঠা করে? / Which organisation established the Thakurgaon Silk Factory in 1976?', 'রেশম বোর্ড', 'বিসিক', 'বিএমআরই', 'আরডিআরএস | RDRS', 'D', 19, 'official');
insert into public.questions (category, question, option_a, option_b, option_c, option_d, correct_answer, order_no, source) values ('Senior', '১৮৭৫ সালে গাইবান্ধা মহকুমার সদর দপ্তর গাইবান্ধায় স্থানান্তরের কারণ কী? / Why was the Gaibandha subdivision HQ moved to Gaibandha in 1875?', 'যুদ্ধ', 'জমিদারদের অনুরোধ', 'ভবানীগঞ্জ নদীগর্ভে বিলীন হওয়া | Bhabaniganj lost to river', 'রেলপথ স্থাপন', 'C', 20, 'official');
